// ─────────────────────────────────────────────────────────────────────────────
// lib/panelDeploy.js — Pterodactyl one-shot deploy script (panel + node + egg)
// for the Panel Hosting page.
//
// The script is written to /root/panel-deploy.sh on the VPS and run with
// nohup so the admin page can poll /root/panel-deploy.log for progress.
//
// Flow: panel (pterodactyl-installer, non-interactive env vars) → Wings
// (docker + binary + systemd) → application API key via the admin session →
// location + node via the application API → wings config.yml + start →
// egg import via the application API (default Minecraft Java egg).
//
// Inputs are sanitized (alphanumeric + limited punctuation) to keep the
// generated bash/JSON safe. Panel URL is optional — falls back to the VPS IP.
// ─────────────────────────────────────────────────────────────────────────────

export const DEFAULT_EGG_URL =
  'https://raw.githubusercontent.com/parkervcp/eggs/master/minecraft/java/paper/egg-paper.json';

const clean = (s, extra = '') => String(s || '').replace(new RegExp(`[^A-Za-z0-9_${extra}]`, 'g'), '').slice(0, 64);

export function buildDeployScript(input) {
  const fqdn = clean(input.panelUrl || input.host, '\\.:'); // panel URL (host/IP) — fallback to VPS IP
  const adminUser = clean(input.adminUser || 'admin', '.');
  const adminPass = clean(input.adminPass, '') || requireRandom(10);
  const adminEmail = clean(input.adminEmail || 'admin@localhost.local', '@\\.-');
  const dbPass = clean(input.dbPass || '', '') || requireRandom(24);
  const nodeName = clean(input.nodeName || 'Node 1', ' -') || 'Node 1';
  const locationShort = clean(input.locationShort || 'US', '') || 'LOC';
  const locationLong = clean(input.locationLong || 'Main location', ' -');
  const nodeMemory = String(Math.max(512, parseInt(input.nodeMemory, 10) || 2048));
  const nodeDisk = String(Math.max(5120, parseInt(input.nodeDisk, 10) || 20480));
  const eggUrl = String(input.eggUrl || DEFAULT_EGG_URL).trim().slice(0, 300);

  return `#!/bin/bash
# AUTO-DEPLOY PTERODACTYL PANEL + NODE + EGG (generated by MZAZI admin)
set -u
LOG=/root/panel-deploy.log
echo "[START] $(date -u +%FT%TZ)" >> "$LOG"

PANEL_FQDN="${fqdn}"
PANEL_URL="http://${fqdn}"
ADMIN_USER="${adminUser}"
ADMIN_PASS="${adminPass}"
ADMIN_EMAIL="${adminEmail}"
DB_PASS="${dbPass}"
NODE_NAME="${nodeName}"
LOCATION_SHORT="${locationShort}"
LOCATION_LONG="${locationLong}"
NODE_MEMORY="${nodeMemory}"
NODE_DISK="${nodeDisk}"
EGG_URL="${eggUrl}"

export GITHUB_BASE_URL="https://raw.githubusercontent.com"
export GITHUB_SOURCE="pterodactyl-installer/pterodactyl-installer"

step() { echo "[STEP] $1" >> "$LOG"; }
ok()   { echo "[OK]   $1" >> "$LOG"; }
fail() { echo "[FAIL] $1" >> "$LOG"; echo "[FINISH] failed" >> "$LOG"; exit 1; }

# ── 0. sanity ──────────────────────────────────────────────────────────────
step "Checking root + existing install"
[ "$(id -u)" = "0" ] || fail "must run as root (ssh as root)"
if [ -d /var/www/pterodactyl ]; then
  fail "a Pterodactyl panel already exists on this machine (/var/www/pterodactyl)"
fi

# ── 1. panel ────────────────────────────────────────────────────────────────
step "Installing Pterodactyl panel (nginx + PHP 8.3 + MariaDB) — a few minutes"
mkdir -p /tmp/ptero-install && cd /tmp/ptero-install
curl -fsSL "$GITHUB_BASE_URL/$GITHUB_SOURCE/master/installers/panel.sh" -o panel.sh || fail "could not download panel installer"
export FQDN="$PANEL_FQDN"
export MYSQL_DB="panel" MYSQL_USER="pterodactyl" MYSQL_PASSWORD="$DB_PASS"
export user_email="$ADMIN_EMAIL" user_username="$ADMIN_USER" user_password="$ADMIN_PASS"
export user_firstname="$ADMIN_USER" user_lastname="Admin"
export email="$ADMIN_EMAIL"
export CONFIGURE_LETSENCRYPT="false" CONFIGURE_FIREWALL="true" ASSUME_SSL="false" timezone="UTC" telemetry="false"
bash panel.sh >> "$LOG" 2>&1 || fail "panel installer failed (see log above)"
ok "Panel installed at $PANEL_URL"

# ── 2. wings (docker + binary + systemd) ─────────────────────────────────────
step "Installing Wings (Docker + daemon binary)"
curl -fsSL "$GITHUB_BASE_URL/$GITHUB_SOURCE/master/installers/wings.sh" -o wings.sh || fail "could not download wings installer"
export INSTALL_MARIADB="false" CONFIGURE_FIREWALL="false" CONFIGURE_DBHOST="false" CONFIGURE_LETSENCRYPT="false"
bash wings.sh >> "$LOG" 2>&1 || fail "wings installer failed"
ok "Wings binary + Docker installed"

# ── 3. application API key via admin session ─────────────────────────────────
step "Creating application API key (auto-deploy)"
JAR=/tmp/ptero-cookies; rm -f "$JAR"
get_csrf() { curl -s -c "$JAR" -b "$JAR" "$1" | grep -oP '(?<=name="_token" value=")[^"]+' | head -1; }
CSRF1=$(get_csrf "$PANEL_URL/auth/login")
[ -n "$CSRF1" ] || fail "could not fetch login CSRF from $PANEL_URL"
curl -s -c "$JAR" -b "$JAR" -X POST "$PANEL_URL/auth/login" -d "_token=$CSRF1&user=$ADMIN_USER&password=$ADMIN_PASS" -o /dev/null
CSRF2=$(get_csrf "$PANEL_URL/admin/api")
[ -n "$CSRF2" ] || fail "admin login failed — wrong credentials?"
KEY_RESP=$(curl -s -c "$JAR" -b "$JAR" -X POST "$PANEL_URL/admin/api" -d "_token=$CSRF2&description=auto-deploy&allowed_ips=" -H "Accept: application/json")
KEY_ID=$(echo "$KEY_RESP" | grep -oP '(?<="identifier":")[^"]+' | head -1)
KEY_SECRET=$(echo "$KEY_RESP" | grep -oP '(?<="token":")[^"]+' | head -1)
[ -n "$KEY_ID" ] && [ -n "$KEY_SECRET" ] || fail "could not parse API key from panel response"
AUTH=""
for candidate in "$KEY_ID$KEY_SECRET" "$KEY_SECRET" "$KEY_ID"; do
  code=$(curl -s -o /dev/null -w "%{http_code}" -H "Authorization: Bearer $candidate" "$PANEL_URL/api/application/users")
  if [ "$code" = "200" ]; then AUTH="$candidate"; break; fi
done
[ -n "$AUTH" ] || fail "API key was created but the panel rejected it"
ok "API key created + verified"

# ── 4. location + node via the application API ───────────────────────────────
step "Creating location '$LOCATION_SHORT' + node '$NODE_NAME'"
LOC=$(curl -s -H "Authorization: Bearer $AUTH" -H "Content-Type: application/json" -X POST "$PANEL_URL/api/application/locations" -d "{\\"short\\":\\"$LOCATION_SHORT\\",\\"long\\":\\"$LOCATION_LONG\\"}")
LOC_ID=$(echo "$LOC" | grep -oP '(?<="id":)[0-9]+' | head -1)
[ -n "$LOC_ID" ] || fail "could not create location: $LOC"
NODE=$(curl -s -H "Authorization: Bearer $AUTH" -H "Content-Type: application/json" -X POST "$PANEL_URL/api/application/nodes" -d "{\\"name\\":\\"$NODE_NAME\\",\\"location_id\\":$LOC_ID,\\"fqdn\\":\\"$PANEL_FQDN\\",\\"scheme\\":\\"http\\",\\"memory\\":$NODE_MEMORY,\\"memory_overallocate\\":0,\\"disk\\":$NODE_DISK,\\"disk_overallocate\\":0,\\"upload_size\\":100,\\"daemon_listen\\":8080,\\"daemon_sftp\\":2022,\\"daemon_base\\":\\"/var/lib/pterodactyl/volumes\\",\\"daemon_public\\":false}")
NODE_ID=$(echo "$NODE" | grep -oP '(?<="id":)[0-9]+' | head -1)
[ -n "$NODE_ID" ] || fail "could not create node: $NODE"
DAEMON_TOKEN_ID=$(echo "$NODE" | grep -oP '(?<="daemon_token_id":")[^"]+' | head -1)
DAEMON_TOKEN=$(echo "$NODE" | grep -oP '(?<="daemon_token":")[^"]+' | head -1)
if [ -z "$DAEMON_TOKEN" ] || [ "$DAEMON_TOKEN" = "null" ]; then
  step "Regenerating daemon token via admin configuration page"
  CFG_HTML=$(curl -s -c "$JAR" -b "$JAR" "$PANEL_URL/admin/nodes/$NODE_ID/configuration")
  DAEMON_TOKEN_ID=$(echo "$CFG_HTML" | grep -oP '(?<=token_id: ).*' | tr -d ' \\r' | head -1)
  DAEMON_TOKEN=$(echo "$CFG_HTML" | grep -oP '(?<=token: ).*' | tr -d ' \\r' | head -1)
  [ -n "$DAEMON_TOKEN" ] && [ "$DAEMON_TOKEN" != "null" ] || fail "could not obtain daemon token for node $NODE_ID"
fi
ok "Node #$NODE_ID created ($NODE_NAME @ $PANEL_FQDN)"

# ── 5. wings config + start ──────────────────────────────────────────────────
step "Writing /etc/pterodactyl/config.yml + starting wings"
mkdir -p /etc/pterodactyl
cat > /etc/pterodactyl/config.yml <<EOF
debug: false
uuid: $NODE_ID
token_id: $DAEMON_TOKEN_ID
token: $DAEMON_TOKEN
api:
  host: 0.0.0.0
  port: 8080
  ssl:
    enabled: false
    cert: /etc/letsencrypt/live/$PANEL_FQDN/fullchain.pem
    key: /etc/letsencrypt/live/$PANEL_FQDN/privkey.pem
system:
  data: /var/lib/pterodactyl/volumes
  sftp:
    bind_port: 2022
allowed_mounts: []
remote: '$PANEL_URL'
EOF
chown root:root /etc/pterodactyl/config.yml && chmod 600 /etc/pterodactyl/config.yml
systemctl start wings || fail "could not start wings service"
ok "Wings daemon running (ports 8080/2022)"

# ── 6. egg import ────────────────────────────────────────────────────────────
step "Importing egg from $EGG_URL"
curl -fsSL "$EGG_URL" -o /tmp/egg.json || fail "could not download egg JSON"
php -r '$d = json_decode(file_get_contents("/tmp/egg.json"), true); $egg = $d["egg"] ?? $d; echo json_encode(["egg" => $egg, "import_to_nest" => 1]);' > /tmp/egg-payload.json || fail "could not build egg payload (php missing?)"
EGG_RESP=$(curl -s -H "Authorization: Bearer $AUTH" -H "Content-Type: application/json" -X POST "$PANEL_URL/api/application/eggs/import" -d @/tmp/egg-payload.json)
EGG_ID=$(echo "$EGG_RESP" | grep -oP '(?<="id":)[0-9]+' | head -1)
if [ -n "$EGG_ID" ]; then ok "Egg imported (id $EGG_ID)"; else echo "[WARN] egg import failed: $EGG_RESP" >> "$LOG"; EGG_ID=""; fi

echo "[DONE] PANEL_URL=$PANEL_URL" >> "$LOG"
echo "[DONE] ADMIN_USER=$ADMIN_USER" >> "$LOG"
echo "[DONE] ADMIN_PASS=$ADMIN_PASS" >> "$LOG"
echo "[DONE] NODE_ID=$NODE_ID" >> "$LOG"
echo "[DONE] EGG_ID=$EGG_ID" >> "$LOG"
echo "[FINISH] complete $(date -u +%FT%TZ)" >> "$LOG"
`;
}

function requireRandom(len) {
  const chars = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
  let out = '';
  const bytes = (globalThis.crypto && crypto.getRandomValues) ? crypto.getRandomValues(new Uint8Array(len)) : null;
  if (bytes) {
    for (let i = 0; i < len; i++) out += chars[bytes[i] % chars.length];
  } else {
    for (let i = 0; i < len; i++) out += chars[Math.floor(Math.random() * chars.length)];
  }
  return out;
}
